### ISSUE TITLE
Software update configuration points at wrong repository & archive URL

### ISSUE THREAD

**Issue by foosel** [l00ma/OctoPrint-roomTemp#17]
This plugin's software update configuration is broken:

https://github.com/l00ma/OctoPrint-roomTemp/blob/1a6f426b9154607dff88322a82c168f8b5f26399/octoprint_roomtemp/__init__.py#L110-L125

It's referring to user `looma` instead of `l00ma` and URL `https://github.com/looma/OctoPrint-roomTemp/archive/{target_version}.zip` instead of `https://github.com/l00ma/OctoPrint-roomTemp/archive/{target_version}.zip`.

Updates won't be found that way and need to be applied manually. You might want to fix this.

Additionally, you need to tag your releases via Github's [release mechanism](https://help.github.com/articles/creating-releases/) or updates *also* won't be found.

**Comment by l00ma** [comment]
Hello,
This plugin is not usable cause I don't use ds18b20 sensor anymore.
I will maybe take time to update it in the future. 
Nevertheless, I have corrected user mistake.
Thank you
